---
language: python
cache: pip
python: "2.7"

# Use a full VM (rather than a sudo-less container), as we need sudo access to
# test this Ansible role.
sudo: true

# The test script will be run against the following versions of Ansible:
env:
  - ANSIBLE_VERSION=2.1.1.0
  - ANSIBLE_VERSION=2.2.0.0

# Install Python's PIP.
addons:
  apt:
    packages:
    - python-pip

install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Install the other required Python libraries.
  #- pip install -r tests/requirements.txt

  # Print the Ansible version to the log.
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic test script syntax check.
  - ansible-playbook tests/test.yml --inventory-file=tests/inventory --syntax-check

  # Run the test script.
  - ansible-playbook tests/test.yml --inventory-file=tests/inventory --connection=local

  # Run the test script again, checking to make sure it's idempotent.
  - >
    ansible-playbook tests/test.yml --inventory-file=tests/inventory --connection=local --skip-tags "test"
    | tee /dev/tty
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

